spring:
  application:
    name: spring-mvc
  datasource:
    username: spring-mvc
    password: Passw0rd   
    url: jdbc:mysql://locahost:3306/spring-mvc
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081