spring:
  application:
    name: spring-mvc
  datasource:
    username: spring_user
    password: Passm0rd
    url: jdbc:mysql://locahost:3306/spring_mvc
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081